-- RideEZ Database Schema
-- This file is provided for reference. The schema will be auto-generated by Hibernate
-- based on the JPA entities when spring.jpa.hibernate.ddl-auto=update

CREATE DATABASE IF NOT EXISTS rideez_db;
USE rideez_db;

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('RIDER', 'PASSENGER') NOT NULL,
    rating DECIMAL(3,2) DEFAULT 0.00,
    INDEX idx_phone (phone),
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Rides Table
CREATE TABLE IF NOT EXISTS rides (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    rider_id BIGINT NOT NULL,
    source_lat DECIMAL(10, 8) NOT NULL,
    source_lng DECIMAL(11, 8) NOT NULL,
    source_address VARCHAR(500),
    dest_lat DECIMAL(10, 8) NOT NULL,
    dest_lng DECIMAL(11, 8) NOT NULL,
    dest_address VARCHAR(500),
    date_time DATETIME NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    status ENUM('CREATED', 'BOOKED', 'ONGOING', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'CREATED',
    available_seats INT NOT NULL DEFAULT 1,
    FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_rider (rider_id),
    INDEX idx_status (status),
    INDEX idx_date_time (date_time),
    INDEX idx_location (source_lat, source_lng)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bookings Table
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ride_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    booking_status ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    booked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ride_id) REFERENCES rides(id) ON DELETE CASCADE,
    FOREIGN KEY (passenger_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_ride_passenger (ride_id, passenger_id),
    INDEX idx_ride (ride_id),
    INDEX idx_passenger (passenger_id),
    INDEX idx_status (booking_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Ratings Table
CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ride_id BIGINT NOT NULL,
    rider_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review VARCHAR(1000),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ride_id) REFERENCES rides(id) ON DELETE CASCADE,
    FOREIGN KEY (rider_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (passenger_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_ride_passenger_rating (ride_id, passenger_id),
    INDEX idx_rider (rider_id),
    INDEX idx_ride (ride_id),
    INDEX idx_passenger (passenger_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



